"""add_tasks_task_submissions_wallet_transactions

Revision ID: 13fa8854eaea
Revises: b7f2c9d4e1a0
Create Date: 2026-06-16 20:57:43.719654

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13fa8854eaea"
down_revision: str | Sequence[str] | None = "b7f2c9d4e1a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("task_type", sa.String(length=20), nullable=False),
        sa.Column("reward_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["child_id"], ["children.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_child_id"), "tasks", ["child_id"], unique=False)
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    op.create_table(
        "task_submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["child_id"], ["children.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "task_id", "scheduled_date", name="uq_task_submissions_task_date"
        ),
    )
    op.create_index(
        op.f("ix_task_submissions_child_id"),
        "task_submissions",
        ["child_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_submissions_id"), "task_submissions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_task_submissions_task_id"),
        "task_submissions",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "wallet_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("task_submission_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("transaction_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["child_id"], ["children.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["task_submission_id"], ["task_submissions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_transactions_child_id"),
        "wallet_transactions",
        ["child_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_transactions_id"), "wallet_transactions", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallet_transactions_id"), table_name="wallet_transactions")
    op.drop_index(
        op.f("ix_wallet_transactions_child_id"), table_name="wallet_transactions"
    )
    op.drop_table("wallet_transactions")
    op.drop_index(op.f("ix_task_submissions_task_id"), table_name="task_submissions")
    op.drop_index(op.f("ix_task_submissions_id"), table_name="task_submissions")
    op.drop_index(op.f("ix_task_submissions_child_id"), table_name="task_submissions")
    op.drop_table("task_submissions")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_child_id"), table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
